 name: gitartwork from a contribution graph
 on: 
   push:
   schedule:
     - cron: "0 */24 * * *"
 jobs:
   build:
     name: Make gitartwork SVG
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - name: Check system info
         run: |
           uname -a
           node --version
       - uses: viettrungIT3/gitartwork@v1
         with:
           user_name: viettrungIT3
           text: Harry.T
       - uses: viettrungIT3/simple-push-action@v1

