 name: gitartwork from a contribution graph
 on: 
   push:
   schedule:
     - cron: "0 */24 * * *"
 jobs:
   build:
     name: Make gitartwork SVG
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
       - uses: viettrungIT3/gitartwork@v1
         with:
            # Use this username's contribution graph  
            user_name: viettrungIT3
            # Text on contribution graph 
            text: Harry.T
       - uses: viettrungIT3/simple-push-action@v1
